=== harvard-lts/fits/xml/fits_output.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" targetNamespace="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="fits">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="statistics" type="statisticsType" minOccurs="0"/>
				<xs:element name="identification" type="identificationType" minOccurs="0"/>
				<xs:element name="fileinfo" type="fileInfoType" minOccurs="0"/>
				<xs:element name="filestatus" type="fileStatusType" minOccurs="0"/>
				<xs:element name="metadata" type="metadataType" minOccurs="0"/>
				<xs:element name="statistics" type="statisticsType" minOccurs="0"/>
				<xs:element name="toolOutput" type="toolOutputType" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="optional"/>
			<xs:attribute name="timestamp" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- Attribute Groups -->
	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SINGLE_RESULT"/>
			<xs:enumeration value="CONFLICT"/>
			<xs:enumeration value="PARTIAL"/>
			<xs:enumeration value="UNKNOWN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="nameVersionStatusAttrGrp">
		<xs:attributeGroup ref="nameVersionAttrGrp"/>
		<xs:attribute name="status" type="statusType" use="optional"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="nameVersionAttrGrp">
		<xs:attribute name="toolname" type="xs:string" use="optional"/>
		<xs:attribute name="toolversion" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<!-- FITS Metadata type -->
	<xs:complexType name="fitsMetadataType">
		<xs:complexContent>
			<xs:extension base="xs:anyType">
				<xs:attributeGroup ref="nameVersionStatusAttrGrp"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Statistics elements -->
	<xs:complexType name="statisticsType">
		<xs:sequence>
			<xs:element name="tool" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attributeGroup ref="nameVersionAttrGrp"/>
					<xs:attribute name="executionTime" type="xs:integer"/>
					<xs:attribute name="status" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="fitsExecutionTime" type="xs:integer"/>
	</xs:complexType>
	<!-- Identification elements-->
	<xs:complexType name="identificationType">
		<xs:sequence>
			<xs:element name="identity" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="tool" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="version" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="externalIdentifier" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="format" type="xs:string"/>
					<xs:attribute name="mimetype" type="xs:string"/>
					<xs:attribute name="toolname" type="xs:string" use="optional"/>
					<xs:attribute name="toolversion" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="status" type="statusType" use="optional"/>
	</xs:complexType>
	<xs:element name="tool">
		<xs:complexType>
			<xs:attributeGroup ref="nameVersionAttrGrp"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="version">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="nameVersionStatusAttrGrp"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="externalIdentifier">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="nameVersionAttrGrp"/>
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!--file info elements-->
	<xs:complexType name="fileInfoType">
		<xs:group ref="fileInfoElements" minOccurs="0" maxOccurs="unbounded"/>
	</xs:complexType>
	<xs:group name="fileInfoElements">
		<xs:choice>
			<xs:element name="filepath" type="fitsMetadataType"/>
			<xs:element name="filename" type="fitsMetadataType"/>
			<xs:element name="size" type="fitsMetadataType"/>
			<xs:element name="md5checksum" type="fitsMetadataType"/>
			<xs:element name="lastmodified" type="fitsMetadataType"/>
			<xs:element name="fslastmodified" type="fitsMetadataType"/>
			<xs:element name="created" type="fitsMetadataType"/>
			<xs:element name="creatingApplicationName" type="fitsMetadataType"/>
			<xs:element name="creatingApplicationVersion" type="fitsMetadataType"/>
			<xs:element name="inhibitorType" type="fitsMetadataType"/>
			<xs:element name="inhibitorTarget" type="fitsMetadataType"/>
			<xs:element name="rightsBasis" type="fitsMetadataType"/>
			<xs:element name="copyrightBasis" type="fitsMetadataType"/>
			<xs:element name="copyrightNote" type="fitsMetadataType"/>
			<xs:element name="creatingos" type="fitsMetadataType"/>
		</xs:choice>
	</xs:group>
	<!-- file status elements -->
	<xs:complexType name="fileStatusType">
		<xs:group ref="fileStatusElements" minOccurs="0" maxOccurs="unbounded"/>
	</xs:complexType>
	<xs:group name="fileStatusElements">
		<xs:choice>
			<xs:element name="well-formed" type="fitsMetadataType"/>
			<xs:element name="valid" type="fitsMetadataType"/>
			<xs:element name="message" type="fitsMetadataType"/>
		</xs:choice>
	</xs:group>
	<!-- metadata types -->
	<xs:complexType name="metadataType">
		<xs:choice>
			<xs:element name="image" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="text" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="document" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="audio" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="video" type="technicalMetadata" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="technicalMetadata">
		<xs:sequence>
			<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- tool output type -->
	<xs:complexType name="toolOutputType">
		<xs:sequence>
			<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== harvard-lts/fits/testfiles/output/P3EKWCX2XYWWB8Y.xml_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.5.2-SNAPSHOT" timestamp="12/30/21, 5:03 PM">
  <identification status="SINGLE_RESULT">
    <identity format="TEI" mimetype="application/tei+xml" toolname="FITS" toolversion="1.5.2-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.5.2" />
      <version toolname="Droid" toolversion="6.5.2">P5</version>
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">fmt/1476</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <size toolname="Jhove" toolversion="1.24.9">235257</size>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/fits/testfiles/P3EKWCX2XYWWB8Y.xml</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">P3EKWCX2XYWWB8Y.xml</filename>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">e4cf29a87057861c560d4d1f0f9491c2</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1640875851368</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata />
  <statistics fitsExecutionTime="178">
    <tool toolname="MediaInfo" toolversion="20.08" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.5" executionTime="117" />
    <tool toolname="Jhove" toolversion="1.24.9" executionTime="825" />
    <tool toolname="file utility" toolversion="5.40" executionTime="876" />
    <tool toolname="Exiftool" toolversion="12.30" executionTime="815" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" executionTime="695" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="100" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" executionTime="90" />
    <tool toolname="ffident" toolversion="0.2" executionTime="637" />
    <tool toolname="Tika" toolversion="2.2.1" executionTime="184" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/assorted-files.zip-default_ZipDisabledXmlUnitTest_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.6.1-SNAPSHOT" timestamp="7/29/23, 6:48 PM">
  <identification>
    <identity format="ZIP Format" mimetype="application/zip" toolname="FITS" toolversion="1.6.1-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.7.0-RC2" />
      <tool toolname="file utility" toolversion="5.43" />
      <tool toolname="Exiftool" toolversion="12.60" />
      <tool toolname="ffident" toolversion="0.2" />
      <tool toolname="Tika" toolversion="2.8.0" />
      <version toolname="file utility" toolversion="5.43">1.0</version>
      <externalIdentifier toolname="Droid" toolversion="6.7.0-RC2" type="puid">x-fmt/263</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/fits/testfiles/input/assorted-files.zip</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">assorted-files.zip</filename>
    <size toolname="OIS File Information" toolversion="1.0">30400659</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">381dd28336fef8e188ebec5c6c29c596</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1666562273086</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata />
  <statistics fitsExecutionTime="2021">
    <tool toolname="MediaInfo" toolversion="23.07" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.7.0-RC2" executionTime="116" />
    <tool toolname="jpylyzer" toolversion="2.1.0" status="did not run" />
    <tool toolname="Jhove" toolversion="1.26.1" status="did not run" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.43" executionTime="473" />
    <tool toolname="Exiftool" toolversion="12.60" executionTime="438" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="115" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="412" />
    <tool toolname="Tika" toolversion="2.8.0" executionTime="2007" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/test.xml_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.2.1" timestamp="4/9/18 4:45 PM">
  <identification>
    <identity format="Extensible Markup Language" mimetype="text/xml" toolname="FITS" toolversion="1.2.1">
      <tool toolname="Droid" toolversion="6.3" />
      <tool toolname="Jhove" toolversion="1.20" />
      <tool toolname="file utility" toolversion="5.31" />
      <tool toolname="Exiftool" toolversion="10.00" />
      <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" />
      <tool toolname="OIS XML Metadata" toolversion="0.2" />
      <tool toolname="ffident" toolversion="0.2" />
      <tool toolname="Tika" toolversion="1.10" />
      <version toolname="Droid" toolversion="6.3">1.0</version>
      <externalIdentifier toolname="Droid" toolversion="6.3" type="puid">fmt/101</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <size toolname="Jhove" toolversion="1.20">3219</size>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/git-daveneiman/fits/testfiles/test.xml</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">test.xml</filename>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">43ebf426e75119483bbea6729ba567e9</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1523306483000</fslastmodified>
  </fileinfo>
  <filestatus>
    <well-formed toolname="Jhove" toolversion="1.20" status="SINGLE_RESULT">true</well-formed>
    <valid toolname="Jhove" toolversion="1.20" status="SINGLE_RESULT">true</valid>
  </filestatus>
  <metadata>
    <text>
      <charset toolname="Jhove" toolversion="1.20">utf-8</charset>
      <markupBasis toolname="Jhove" toolversion="1.20">XML</markupBasis>
      <markupBasisVersion toolname="Jhove" toolversion="1.20">1.0</markupBasisVersion>
      <markupLanguage toolname="OIS XML Metadata" toolversion="0.2" status="SINGLE_RESULT">http://www.loc.gov/standards/mets/mets.xsd</markupLanguage>
    </text>
  </metadata>
  <statistics fitsExecutionTime="1430">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.3" executionTime="270" />
    <tool toolname="Jhove" toolversion="1.20" executionTime="1386" />
    <tool toolname="file utility" toolversion="5.31" executionTime="613" />
    <tool toolname="Exiftool" toolversion="10.00" executionTime="614" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" executionTime="590" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="204" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" executionTime="261" />
    <tool toolname="ffident" toolversion="0.2" executionTime="586" />
    <tool toolname="Tika" toolversion="1.10" executionTime="438" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/Winnie-the-Pooh-protected.epub_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.11.0" timestamp="2/12/16 10:01 AM">
  <identification>
    <identity format="EPUB" mimetype="application/epub+zip" toolname="FITS" toolversion="0.11.0">
      <tool toolname="Exiftool" toolversion="10.00" />
      <tool toolname="Tika" toolversion="1.10" />
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/fits-daveneiman/fits/testfiles/Winnie-the-Pooh-protected.epub</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">Winnie-the-Pooh-protected.epub</filename>
    <size toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">15107043</size>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">4ccb561ddebda70324926895899cd27c</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1453908574000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <document>
      <title toolname="Exiftool" toolversion="10.00">Winnie-the-Pooh</title>
      <author toolname="Exiftool" toolversion="10.00">A. A. Milne</author>
      <isRightsManaged toolname="Exiftool" toolversion="10.00">yes</isRightsManaged>
      <identifier toolname="Exiftool" toolversion="10.00">1-101-15893-X</identifier>
      <language toolname="Exiftool" toolversion="10.00">en</language>
      <standard>
        <docmd:document xmlns:docmd="http://www.fcla.edu/docmd">
          <docmd:Language>en</docmd:Language>
        </docmd:document>
      </standard>
    </document>
  </metadata>
  <statistics fitsExecutionTime="234">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.1.5" executionTime="70" />
    <tool toolname="Jhove" toolversion="1.11" status="did not run" />
    <tool toolname="file utility" toolversion="5.04" status="did not run" />
    <tool toolname="Exiftool" toolversion="10.00" executionTime="228" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="68" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="8" />
    <tool toolname="Tika" toolversion="1.10" executionTime="101" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/KXXJXH4YTGWQ68W.kml_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.5.2-SNAPSHOT" timestamp="12/29/21, 12:14 PM">
  <identification>
    <identity format="Keyhole Markup Language" mimetype="application/vnd.google-earth.kml+xml" toolname="FITS" toolversion="1.5.2-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.5.2" />
      <tool toolname="Tika" toolversion="2.3.0" />
      <externalIdentifier toolname="Droid" toolversion="6.5.2" type="puid">fmt/244</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <size toolname="Jhove" toolversion="1.20.1">36669</size>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/fits/testfiles/KXXJXH4YTGWQ68W.kml</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">KXXJXH4YTGWQ68W.kml</filename>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">ec82a6c4853cfb5a3728ab15105cb189</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1640797174095</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata />
  <statistics fitsExecutionTime="243">
    <tool toolname="MediaInfo" toolversion="20.08" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.4" executionTime="8" />
    <tool toolname="Jhove" toolversion="1.20.1" executionTime="59" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.41" executionTime="59" />
    <tool toolname="Exiftool" toolversion="11.54" executionTime="222" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="1" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="2" />
    <tool toolname="Tika" toolversion="2.2.1" executionTime="43" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/WordPerfect5_0.wp_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.2.x" timestamp="2/2/18 5:12 PM">
  <identification>
    <identity format="WordPerfect Document" mimetype="application/vnd.wordperfect" toolname="FITS" toolversion="1.2.x">
      <tool toolname="Droid" toolversion="6.3" />
      <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" />
      <version toolname="Droid" toolversion="6.3">5.0</version>
      <externalIdentifier toolname="Droid" toolversion="6.3" type="puid">x-fmt/393</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <creatingApplicationName toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="SINGLE_RESULT">WordPerfect</creatingApplicationName>
    <creatingApplicationVersion toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="SINGLE_RESULT">5.0</creatingApplicationVersion>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/git-daveneiman/fits/testfiles/WordPerfect5_0.wp</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">WordPerfect5_0.wp</filename>
    <size toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">3329</size>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">dd08b1df84b3d38736ac777795566b42</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1516117983000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <document>
      <title toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="SINGLE_RESULT">Kafka - Metamorphosis Sampel WP document</title>
      <author toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="SINGLE_RESULT">viz765</author>
      <standard>
        <docmd:document xmlns:docmd="http://www.fcla.edu/docmd" />
      </standard>
    </document>
  </metadata>
  <statistics fitsExecutionTime="125">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.3" executionTime="12" />
    <tool toolname="Jhove" toolversion="1.16" status="did not run" />
    <tool toolname="file utility" toolversion="5.31" executionTime="49" />
    <tool toolname="Exiftool" toolversion="10.00" executionTime="163" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" executionTime="35" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="3" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="7" />
    <tool toolname="Tika" toolversion="1.10" executionTime="6" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/WordPerfect6-7.wpd_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.11.0" timestamp="3/22/16 12:31 PM">
  <identification>
    <identity format="WordPerfect Document" mimetype="application/vnd.wordperfect" toolname="FITS" toolversion="0.11.0">
      <tool toolname="Droid" toolversion="6.1.5" />
      <tool toolname="file utility" toolversion="5.04" />
      <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" />
      <version toolname="Droid" toolversion="6.1.5">6.0</version>
      <externalIdentifier toolname="Droid" toolversion="6.1.5" type="puid">x-fmt/44</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <creatingApplicationName toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="SINGLE_RESULT">WordPerfect</creatingApplicationName>
    <creatingApplicationVersion toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="SINGLE_RESULT">7.1</creatingApplicationVersion>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/fits-daveneiman/fits/testfiles/WordPerfect6-7.wpd</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">WordPerfect6-7.wpd</filename>
    <size toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">9122</size>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">12a73e2a0645548d48a7e3c97002aac2</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1454956776000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <document />
  </metadata>
  <statistics fitsExecutionTime="138">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.1.5" executionTime="5" />
    <tool toolname="Jhove" toolversion="1.11" status="did not run" />
    <tool toolname="file utility" toolversion="5.04" executionTime="31" />
    <tool toolname="Exiftool" toolversion="10.00" executionTime="134" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" executionTime="15" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="2" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="7" />
    <tool toolname="Tika" toolversion="1.10" executionTime="6" />
  </statistics>
</fits>
