=== harvard-lts/fits/xml/fits_output.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" targetNamespace="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="fits">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="statistics" type="statisticsType" minOccurs="0"/>
				<xs:element name="identification" type="identificationType" minOccurs="0"/>
				<xs:element name="fileinfo" type="fileInfoType" minOccurs="0"/>
				<xs:element name="filestatus" type="fileStatusType" minOccurs="0"/>
				<xs:element name="metadata" type="metadataType" minOccurs="0"/>
				<xs:element name="statistics" type="statisticsType" minOccurs="0"/>
				<xs:element name="toolOutput" type="toolOutputType" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="version" type="xs:string" use="optional"/>
			<xs:attribute name="timestamp" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<!-- Attribute Groups -->
	<xs:simpleType name="statusType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SINGLE_RESULT"/>
			<xs:enumeration value="CONFLICT"/>
			<xs:enumeration value="PARTIAL"/>
			<xs:enumeration value="UNKNOWN"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:attributeGroup name="nameVersionStatusAttrGrp">
		<xs:attributeGroup ref="nameVersionAttrGrp"/>
		<xs:attribute name="status" type="statusType" use="optional"/>
	</xs:attributeGroup>
	<xs:attributeGroup name="nameVersionAttrGrp">
		<xs:attribute name="toolname" type="xs:string" use="optional"/>
		<xs:attribute name="toolversion" type="xs:string" use="optional"/>
	</xs:attributeGroup>
	<!-- FITS Metadata type -->
	<xs:complexType name="fitsMetadataType">
		<xs:complexContent>
			<xs:extension base="xs:anyType">
				<xs:attributeGroup ref="nameVersionStatusAttrGrp"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<!-- Statistics elements -->
	<xs:complexType name="statisticsType">
		<xs:sequence>
			<xs:element name="tool" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attributeGroup ref="nameVersionAttrGrp"/>
					<xs:attribute name="executionTime" type="xs:integer"/>
					<xs:attribute name="status" type="xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="fitsExecutionTime" type="xs:integer"/>
	</xs:complexType>
	<!-- Identification elements-->
	<xs:complexType name="identificationType">
		<xs:sequence>
			<xs:element name="identity" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="tool" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="version" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="externalIdentifier" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="format" type="xs:string"/>
					<xs:attribute name="mimetype" type="xs:string"/>
					<xs:attribute name="toolname" type="xs:string" use="optional"/>
					<xs:attribute name="toolversion" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="status" type="statusType" use="optional"/>
	</xs:complexType>
	<xs:element name="tool">
		<xs:complexType>
			<xs:attributeGroup ref="nameVersionAttrGrp"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="version">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="nameVersionStatusAttrGrp"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="externalIdentifier">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attributeGroup ref="nameVersionAttrGrp"/>
					<xs:attribute name="type" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!--file info elements-->
	<xs:complexType name="fileInfoType">
		<xs:group ref="fileInfoElements" minOccurs="0" maxOccurs="unbounded"/>
	</xs:complexType>
	<xs:group name="fileInfoElements">
		<xs:choice>
			<xs:element name="filepath" type="fitsMetadataType"/>
			<xs:element name="filename" type="fitsMetadataType"/>
			<xs:element name="size" type="fitsMetadataType"/>
			<xs:element name="md5checksum" type="fitsMetadataType"/>
			<xs:element name="lastmodified" type="fitsMetadataType"/>
			<xs:element name="fslastmodified" type="fitsMetadataType"/>
			<xs:element name="created" type="fitsMetadataType"/>
			<xs:element name="creatingApplicationName" type="fitsMetadataType"/>
			<xs:element name="creatingApplicationVersion" type="fitsMetadataType"/>
			<xs:element name="inhibitorType" type="fitsMetadataType"/>
			<xs:element name="inhibitorTarget" type="fitsMetadataType"/>
			<xs:element name="rightsBasis" type="fitsMetadataType"/>
			<xs:element name="copyrightBasis" type="fitsMetadataType"/>
			<xs:element name="copyrightNote" type="fitsMetadataType"/>
			<xs:element name="creatingos" type="fitsMetadataType"/>
		</xs:choice>
	</xs:group>
	<!-- file status elements -->
	<xs:complexType name="fileStatusType">
		<xs:group ref="fileStatusElements" minOccurs="0" maxOccurs="unbounded"/>
	</xs:complexType>
	<xs:group name="fileStatusElements">
		<xs:choice>
			<xs:element name="well-formed" type="fitsMetadataType"/>
			<xs:element name="valid" type="fitsMetadataType"/>
			<xs:element name="message" type="fitsMetadataType"/>
		</xs:choice>
	</xs:group>
	<!-- metadata types -->
	<xs:complexType name="metadataType">
		<xs:choice>
			<xs:element name="image" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="text" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="document" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="audio" type="technicalMetadata" minOccurs="0"/>
			<xs:element name="video" type="technicalMetadata" minOccurs="0"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="technicalMetadata">
		<xs:sequence>
			<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<!-- tool output type -->
	<xs:complexType name="toolOutputType">
		<xs:sequence>
			<xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== harvard-lts/fits/testfiles/output/valid.xls_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.5.0" timestamp="8/11/21, 9:58 AM">
  <identification>
    <identity format="Microsoft Excel" mimetype="application/vnd.ms-excel" toolname="FITS" toolversion="1.5.0">
      <tool toolname="Droid" toolversion="6.5" />
      <tool toolname="file utility" toolversion="5.39" />
      <tool toolname="Exiftool" toolversion="12.29" />
      <tool toolname="ffident" toolversion="0.2" />
      <tool toolname="Tika" toolversion="2.0.0" />
      <version toolname="Droid" toolversion="6.5">8</version>
      <externalIdentifier toolname="Droid" toolversion="6.5" type="puid">fmt/61</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <created toolname="Exiftool" toolversion="12.29" status="CONFLICT">1998:12:08 14:22:55</created>
    <created toolname="Tika" toolversion="2.0.0" status="CONFLICT">1998-12-08T14:22:55Z</created>
    <creatingApplicationName toolname="Tika" toolversion="2.0.0" status="SINGLE_RESULT">Microsoft Excel</creatingApplicationName>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/home/winckles/workspace/3rd-party/fits/testfiles/valid.xls</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">valid.xls</filename>
    <size toolname="OIS File Information" toolversion="1.0">270336</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">fa11d8719f82d99f034a9ab2e52ac446</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1628692993248</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <document>
      <title toolname="Exiftool" toolversion="12.29">Validatie 1</title>
      <author toolname="Exiftool" toolversion="12.29">Johan van der Knijff</author>
      <standard>
        <docmd:document xmlns:docmd="http://www.fcla.edu/docmd" />
      </standard>
    </document>
  </metadata>
  <statistics fitsExecutionTime="1165">
    <tool toolname="MediaInfo" toolversion="21.03" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.5" executionTime="412" />
    <tool toolname="Jhove" toolversion="1.24.0" executionTime="1116" />
    <tool toolname="file utility" toolversion="5.39" executionTime="1138" />
    <tool toolname="Exiftool" toolversion="12.29" executionTime="1106" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="362" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="1064" />
    <tool toolname="Tika" toolversion="2.0.0" executionTime="780" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/samplepptx.pptx_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.5.0" timestamp="8/11/21, 10:17 AM">
  <identification>
    <identity format="Office Open XML Presentation" mimetype="application/vnd.openxmlformats-officedocument.presentationml.presentation" toolname="FITS" toolversion="1.5.0">
      <tool toolname="Droid" toolversion="6.5" />
      <tool toolname="file utility" toolversion="5.39" />
      <tool toolname="Exiftool" toolversion="12.29" />
      <tool toolname="Tika" toolversion="2.0.0" />
      <version toolname="Droid" toolversion="6.5">2007 onwards</version>
      <externalIdentifier toolname="Droid" toolversion="6.5" type="puid">fmt/215</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <lastmodified toolname="Exiftool" toolversion="12.29" status="CONFLICT">2009:05:06 22:13:30Z</lastmodified>
    <lastmodified toolname="Tika" toolversion="2.0.0" status="CONFLICT">2009-05-06T22:13:30Z</lastmodified>
    <created toolname="Exiftool" toolversion="12.29" status="CONFLICT">2009:05:06 22:06:09Z</created>
    <created toolname="Tika" toolversion="2.0.0" status="CONFLICT">2009-05-06T22:06:09Z</created>
    <creatingApplicationName toolname="Tika" toolversion="2.0.0" status="SINGLE_RESULT">Microsoft Office PowerPoint</creatingApplicationName>
    <creatingApplicationVersion toolname="Tika" toolversion="2.0.0" status="SINGLE_RESULT">12.0000</creatingApplicationVersion>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/home/winckles/workspace/3rd-party/fits/testfiles/samplepptx.pptx</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">samplepptx.pptx</filename>
    <size toolname="OIS File Information" toolversion="1.0">413895</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">72432c9fb76cf45094c29fc92c4b16f0</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1509024961000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <document>
      <pageCount toolname="Tika" toolversion="2.0.0" status="SINGLE_RESULT">2</pageCount>
      <wordCount toolname="Exiftool" toolversion="12.29">30</wordCount>
      <title toolname="Exiftool" toolversion="12.29">Sample PowerPoint File</title>
      <author toolname="Exiftool" toolversion="12.29">James Falkofske</author>
      <paragraphCount toolname="Exiftool" toolversion="12.29">5</paragraphCount>
      <standard>
        <docmd:document xmlns:docmd="http://www.fcla.edu/docmd">
          <docmd:PageCount>2</docmd:PageCount>
          <docmd:WordCount>30</docmd:WordCount>
          <docmd:ParagraphCount>5</docmd:ParagraphCount>
        </docmd:document>
      </standard>
    </document>
  </metadata>
  <statistics fitsExecutionTime="1898">
    <tool toolname="MediaInfo" toolversion="21.03" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.5" executionTime="258" />
    <tool toolname="Jhove" toolversion="1.24.0" executionTime="1099" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.39" executionTime="1122" />
    <tool toolname="Exiftool" toolversion="12.29" executionTime="1110" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="212" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="1037" />
    <tool toolname="Tika" toolversion="2.0.0" executionTime="1836" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/PDFa_has_table_of_contents.pdf_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.3.1" timestamp="9/18/18 4:36 PM">
  <identification>
    <identity format="PDF/A" mimetype="application/pdf" toolname="FITS" toolversion="1.3.1">
      <tool toolname="Droid" toolversion="6.4" />
      <tool toolname="Exiftool" toolversion="11.01" />
      <tool toolname="Tika" toolversion="1.18" />
      <version toolname="Droid" toolversion="6.4">1b</version>
      <externalIdentifier toolname="Droid" toolversion="6.4" type="puid">fmt/354</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <size toolname="Jhove" toolversion="1.20">357428</size>
    <creatingApplicationName toolname="Jhove" toolversion="1.20">Adobe PDF Library 11.0/Acrobat PDFMaker 11 for Word</creatingApplicationName>
    <lastmodified toolname="Exiftool" toolversion="11.01" status="CONFLICT">2015:08:19 18:15:37-04:00</lastmodified>
    <lastmodified toolname="Tika" toolversion="1.18" status="CONFLICT">2015-08-19T22:15:37Z</lastmodified>
    <created toolname="Exiftool" toolversion="11.01" status="SINGLE_RESULT">2015:08:19 16:44:12-04:00</created>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/git-daveneiman/fits/testfiles/PDFa_has_table_of_contents.pdf</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">PDFa_has_table_of_contents.pdf</filename>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">537d5a41d854b5c03f8bb33041faf1aa</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1516117983000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <document>
      <pageCount toolname="Exiftool" toolversion="11.01">5</pageCount>
      <title toolname="Exiftool" toolversion="11.01">Digital Repository Services (DRS) User Manual for Data Loading</title>
      <author toolname="Exiftool" toolversion="11.01">viz765</author>
      <language toolname="Exiftool" toolversion="11.01">EN-US</language>
      <isTagged toolname="Exiftool" toolversion="11.01" status="SINGLE_RESULT">yes</isTagged>
      <standard>
        <docmd:document xmlns:docmd="http://www.fcla.edu/docmd">
          <docmd:PageCount>5</docmd:PageCount>
          <docmd:Language>EN-US</docmd:Language>
          <docmd:Features>isTagged</docmd:Features>
        </docmd:document>
      </standard>
    </document>
  </metadata>
  <statistics fitsExecutionTime="702">
    <tool toolname="MediaInfo" toolversion="18.08.1" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.4" executionTime="13" />
    <tool toolname="Jhove" toolversion="1.20" executionTime="153" />
    <tool toolname="file utility" toolversion="5.31" executionTime="555" />
    <tool toolname="Exiftool" toolversion="11.01" executionTime="694" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" executionTime="64" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="7" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="10" />
    <tool toolname="Tika" toolversion="1.18" executionTime="89" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/assorted-files.zip-default_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.5.0-SNAPSHOT" timestamp="7/10/19 9:19 AM">
  <identification>
    <identity format="ZIP Format" mimetype="application/zip" toolname="FITS" toolversion="1.5.0-SNAPSHOT">
      <tool toolname="Droid" toolversion="6.4" />
      <tool toolname="file utility" toolversion="5.31" />
      <tool toolname="Exiftool" toolversion="11.54" />
      <tool toolname="ffident" toolversion="0.2" />
      <tool toolname="Tika" toolversion="1.21" />
      <version toolname="file utility" toolversion="5.31">1.0</version>
      <externalIdentifier toolname="Droid" toolversion="6.4" type="puid">x-fmt/263</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/git-daveneiman/fits/testfiles/assorted-files.zip</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">assorted-files.zip</filename>
    <size toolname="OIS File Information" toolversion="0.2">30400659</size>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">381dd28336fef8e188ebec5c6c29c596</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1516117983000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <container>
      <originalSize toolname="Droid" toolversion="6.4" status="SINGLE_RESULT">34318329</originalSize>
      <compressionMethod toolname="Droid" toolversion="6.4" status="SINGLE_RESULT">deflate</compressionMethod>
      <entries totalEntries="17" toolname="Droid" toolversion="6.4" status="SINGLE_RESULT">
        <format name="EPUB" number="1" />
        <format name="Extensible Markup Language" number="1" />
        <format name="Graphics Interchange Format" number="1" />
        <format name="JPEG 2000 JP2" number="1" />
        <format name="JPEG File Interchange Format" number="1" />
        <format name="MPEG-4" number="1" />
        <format name="Office Open XML Document" number="1" />
        <format name="OpenDocument Text" number="1" />
        <format name="PDF/A" number="1" />
        <format name="PDF/X" number="1" />
        <format name="Plain text" number="1" />
        <format name="Portable Network Graphics" number="1" />
        <format name="Rich Text Format (RTF)" number="1" />
        <format name="TIFF EXIF" number="1" />
        <format name="Waveform Audio" number="2" />
        <format name="ZIP Format" number="1" />
      </entries>
    </container>
  </metadata>
  <statistics fitsExecutionTime="1013">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.4" executionTime="794" />
    <tool toolname="Jhove" toolversion="1.20.1" status="did not run" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.31" executionTime="568" />
    <tool toolname="Exiftool" toolversion="11.54" executionTime="263" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="142" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="11" />
    <tool toolname="Tika" toolversion="1.21" executionTime="1005" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/utf16.txt_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="0.11.0" timestamp="3/1/16 4:39 PM">
  <identification>
    <identity format="Plain text" mimetype="text/plain" toolname="FITS" toolversion="0.11.0">
      <tool toolname="Droid" toolversion="6.1.5" />
      <tool toolname="file utility" toolversion="5.04" />
      <externalIdentifier toolname="Droid" toolversion="6.1.5" type="puid">x-fmt/111</externalIdentifier>
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">/Users/dan179/git/fits-daveneiman/fits/testfiles/utf16.txt</filepath>
    <filename toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">utf16.txt</filename>
    <size toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">30</size>
    <md5checksum toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">fbb8ef84677fad5a798cef6cf69aef1d</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="0.2" status="SINGLE_RESULT">1446674963000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata>
    <text>
      <charset toolname="file utility" toolversion="5.04" status="SINGLE_RESULT">UTF-16LE</charset>
      <standard>
        <textMD:textMD xmlns:textMD="info:lc/xmlns/textMD-v3">
          <textMD:character_info>
            <textMD:charset>UTF-16LE</textMD:charset>
          </textMD:character_info>
        </textMD:textMD>
      </standard>
    </text>
  </metadata>
  <statistics fitsExecutionTime="524">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.1.5" executionTime="24" />
    <tool toolname="Jhove" toolversion="1.11" executionTime="205" />
    <tool toolname="file utility" toolversion="5.04" executionTime="142" />
    <tool toolname="Exiftool" toolversion="10.00" status="did not run" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="0.2" executionTime="90" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="279" />
    <tool toolname="Tika" toolversion="1.10" executionTime="172" />
  </statistics>
</fits>

=== harvard-lts/fits/testfiles/output/WordPasswordProtected.docx_XmlUnitExpectedOutput.xml
<?xml version="1.0" encoding="UTF-8"?>
<fits xmlns="http://hul.harvard.edu/ois/xml/ns/fits/fits_output" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hul.harvard.edu/ois/xml/ns/fits/fits_output http://hul.harvard.edu/ois/xml/xsd/fits/fits_output.xsd" version="1.5.0" timestamp="12/6/21 3:56 PM">
  <identification status="CONFLICT">
    <identity format="OLE 2 Compound Document, v3.62, SecID 0x1, 11 FAT sectors, Mini FAT start sector 0x2 : UNKNOWN with names EncryptedPackage \006DataSpaces Version" mimetype="application/x-ole-storage" toolname="FITS" toolversion="1.5.0">
      <tool toolname="file utility" toolversion="5.39" />
    </identity>
    <identity format="Office Open XML Document" mimetype="application/vnd.openxmlformats-officedocument.wordprocessingml.document" toolname="FITS" toolversion="1.5.0">
      <tool toolname="Exiftool" toolversion="11.54" />
    </identity>
    <identity format="Microsoft Excel" mimetype="application/vnd.ms-excel" toolname="FITS" toolversion="1.5.0">
      <tool toolname="ffident" toolversion="0.2" />
    </identity>
    <identity format="Password Protected OOXML File" mimetype="application/x-tika-ooxml-protected" toolname="FITS" toolversion="1.5.0">
      <tool toolname="Tika" toolversion="1.21" />
    </identity>
  </identification>
  <fileinfo>
    <filepath toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">/Users/dan179/git/git-daveneiman/fits/testfiles/WordPasswordProtected.docx</filepath>
    <filename toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">WordPasswordProtected.docx</filename>
    <size toolname="OIS File Information" toolversion="1.0">242176</size>
    <md5checksum toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">bfc6125db60e834e6b9e7210970a6233</md5checksum>
    <fslastmodified toolname="OIS File Information" toolversion="1.0" status="SINGLE_RESULT">1516117983000</fslastmodified>
  </fileinfo>
  <filestatus />
  <metadata />
  <statistics fitsExecutionTime="201">
    <tool toolname="MediaInfo" toolversion="0.7.75" status="did not run" />
    <tool toolname="OIS Audio Information" toolversion="0.1" status="did not run" />
    <tool toolname="ADL Tool" toolversion="0.1" status="did not run" />
    <tool toolname="VTT Tool" toolversion="0.1" status="did not run" />
    <tool toolname="Droid" toolversion="6.4" executionTime="8" />
    <tool toolname="Jhove" toolversion="1.20.1" status="did not run" />
    <tool toolname="embARC" toolversion="0.2" status="did not run" />
    <tool toolname="file utility" toolversion="5.39" executionTime="39" />
    <tool toolname="Exiftool" toolversion="11.54" executionTime="199" />
    <tool toolname="NLNZ Metadata Extractor" toolversion="3.6GA" status="did not run" />
    <tool toolname="OIS File Information" toolversion="1.0" executionTime="5" />
    <tool toolname="OIS XML Metadata" toolversion="0.2" status="did not run" />
    <tool toolname="ffident" toolversion="0.2" executionTime="4" />
    <tool toolname="Tika" toolversion="1.21" executionTime="145" />
  </statistics>
</fits>
